/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSDate, NSString;

__attribute__((visibility("hidden")))
@interface ADAccount : XXUnknownSuperclass {
	NSString* _identifier;
	NSString* _label;
	NSString* _assistantIdentifier;
	NSString* _speechIdentifier;
	NSString* _hostname;
	NSString* _aceHost;
	NSString* _localeIdentifier;
	NSString* _lastAssistantDataAnchor;
	NSMutableDictionary* _syncTimestamps;
	NSDate* _validationExpiration;
	BOOL _needsDestruction;
}
@property(assign, nonatomic) BOOL needsDestruction;
@property(copy, nonatomic) NSDate* validationExpiration;
@property(copy, nonatomic) NSString* lastAssistantDataAnchor;
@property(copy, nonatomic) NSString* localeIdentifier;
@property(copy, nonatomic) NSString* aceHost;
@property(copy, nonatomic) NSString* hostname;
@property(copy, nonatomic) NSString* speechIdentifier;
@property(copy, nonatomic) NSString* assistantIdentifier;
@property(copy, nonatomic) NSString* label;
@property(copy, nonatomic) NSString* identifier;
+(id)accountForIdentifier:(id)identifier;
-(void)removeAndSave;
-(void)save;
-(id)_infoDictionaryForPreferences;
-(BOOL)_setKeychainValue:(id)value forKey:(id)key;
-(BOOL)_removeKeychainValueForKey:(id)key;
-(id)_keychainValueForKey:(id)key;
-(void)clearAssistantData;
-(BOOL)setValidationData:(id)data;
-(id)validationData;
-(BOOL)setServerCertificateData:(id)data;
-(id)serverCertificateData;
-(void)setLastSyncDate:(id)date forKey:(id)key;
-(id)lastSyncDateForKey:(id)key;
-(void)_setSyncTimestamps:(id)timestamps;
-(id)messageDictionary;
-(void)dealloc;
@end

